services:
  postgre:
    image: postgres:13.13
    ports:
     - 5432:5432
    networks:
      - kubenews_net
    environment:
      POSTGRES_PASSWORD: pg1234
      POSTGRES_USER: kubenews
      POSTGRES_DB: kubenews

  kubenews:
    image: fabricioveronez/kube-news:v1
    depends_on:
      - postgre
    build:
      context: ./src
      dockerfile: ./Dockerfile
    networks:
      - kubenews_net
    ports: 
      - 8080:8080
    environment:
      DB_DATABASE: kubenews
      DB_USERNAME: kubenews
      DB_PASSWORD: pg1234
      DB_HOST: postgre

networks:
  kubenews_net:
    driver: bridge
