FROM node:21.6.0

# Instalação do Trivy
RUN apt-get update && apt-get install --yes wget apt-transport-https gnupg lsb-release && \
    wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | tee /usr/share/keyrings/trivy.gpg > /dev/null && \
    echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | tee -a /etc/apt/sources.list.d/trivy.list && \
    apt-get update && apt-get install trivy --yes

ADD --chown=nobody:nogroup https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 /usr/local/bin/hadolint
RUN chmod 777 /usr/local/bin/hadolint
USER node
WORKDIR /app
EXPOSE 8080
CMD ["tail", "-f", "/dev/null"]
