name: Install

on:
  workflow_dispatch:
      
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Instalação do ffmpeg
      run: |
        apt update --yes 
        apt install ffmpeg --yes
    - name: Execução do ffmpeg
      run: |
        ffmpeg --help



          
