name: Install

on:
  workflow_dispatch:
      
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        env:
          CONTEXT: ${{ toJson(github) }}
        run: echo "$CONTEXT"



          
