name: CI-CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write

    steps:
    - name: Obtendo o código
      uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}}
    - name: Construção da imagem Docker worker
      uses: docker/build-push-action@v5.0.0
      with: 
        context: ./src
        file: ./src/Dockerfile
        push: false
        tags: |
          fabricioveronez/kube-news:${{github.run_number}}
          fabricioveronez/kube-news:latest                

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.16.1
      with:
        image-ref: fabricioveronez/kube-news:${{github.run_number}}
        format: 'sarif'
        output: 'trivy-results.sarif'
        exit-code: 0
        severity: UNKNOWN,CRITICAL,HIGH,MEDIUM,LOW

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Enviando a imagem
      run: |
        docker push fabricioveronez/kube-news:${{github.run_number}}
        docker push fabricioveronez/kube-news:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/aks-set-context@v3
      with:
          resource-group: live
          cluster-name: live
    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v4.9
      with:
        manifests: |
          ./k8s/deployment.yaml
        images: |
          fabricioveronez/kube-news:${{github.run_number}}



          
