name: tf-k8s

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'terraform/**'
  pull_request:
    branches: [ "main" ]

jobs:
  CD:
    runs-on: ubuntu-latest
    
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v3

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3

    - name: Terraform Validate
      working-directory: ./terraform
      run: terraform validate
      
    - name: Terraform Plan
      working-directory: ./terraform
      run: terraform plan --auto-approve
   
